#!/bin/sh

set -e

rm -f x64sc*
rm -Rf fsbuild/_build

echo "Downloading vice-3.6.1.tar.gz..."
URL=https://netix.dl.sourceforge.net/project/vice-emu/releases/vice-3.6.1.tar.gz
SHA256=20df84c851aaf2f5000510927f6d31b32f269916d351465c366dc0afc9dc150c
python3 fsbuild/download.py "$URL" sha256:$SHA256

echo "Extracting vice-3.6.1.tar.gz..."
mkdir -p fsbuild/_build
cd fsbuild/_build
rm -Rf vice-3.6.1 vice-src
tar xf ../_sources/vice-3.6.1.tar.gz
mv vice-3.6.1 vice-src

echo "Applying patches..."
cd vice-src
patch -p1 < ../../../sysfile.patch
cd ..

# echo "Running autogen.sh..."
# cd vice-src
# ./autogen.sh

echo "Bootstrap done"
