#!/bin/sh
set -e

# FIXME: tiff?
# FIXME: jpeg?
# FIXME: webp?

fsdeps/dep/libpng
fsdeps/dep/SDL2

PACKAGE=SDL2_image-2.0.5
URL="https://www.libsdl.org/projects/SDL_image/release/$PACKAGE.tar.gz"
SHA256=bdd5f6e026682f7d7e1be0b6051b209da2f402a2dd8bd1c4bd9c25ad263108d0
REVISION=1

. fsdeps/dep.sh

if [ $SYSTEM_OS = "Windows" ]; then
URL="https://www.libsdl.org/projects/SDL_image/release/$PACKAGE.zip"
SHA256=eee0927d1e7819d57c623fe3e2b3c6761c77c474fe9bc425e8674d30ac049b1c
fi
python3 fsdeps/download.py "$URL" sha256:$SHA256

rm -Rf fsdeps/_build && mkdir fsdeps/_build && cd fsdeps/_build
if [ $SYSTEM_OS = "Windows" ]; then
unzip ../_sources/$PACKAGE.zip
else
tar xf ../_sources/$PACKAGE.tar.gz
fi
cd $PACKAGE

./configure --prefix=$PREFIX
make
make install

touch $INSTALLED
