#!/bin/sh
set -e

# FIXME: tiff?
# FIXME: jpeg?
# FIXME: webp?

fsdeps/dep/libpng
fsdeps/dep/SDL2

PACKAGE=SDL2_image-2.0.5
CHECKSUM=bdd5f6e026682f7d7e1be0b6051b209da2f402a2dd8bd1c4bd9c25ad263108d0
REVISION=0

. fsdeps/dep.sh

python3 fsdeps/download.py \
https://www.libsdl.org/projects/SDL_image/release/$PACKAGE.tar.gz \
sha256:$CHECKSUM

rm -Rf fsdeps/_build && mkdir fsdeps/_build && cd fsdeps/_build
# if [ "`uname -o`" = "Msys" ]; then
# unzip ../_sources/$PACKAGE.zip
# else
tar xf ../_sources/$PACKAGE.tar.gz
# fi
cd $PACKAGE

./configure --prefix=$PREFIX
make
make install

touch $INSTALLED
